// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana
{
    public partial class DataSource : Pulumi.CustomResource
    {
        [Output("accessMode")]
        public Output<string?> AccessMode { get; private set; } = null!;

        [Output("basicAuthEnabled")]
        public Output<bool?> BasicAuthEnabled { get; private set; } = null!;

        [Output("basicAuthPassword")]
        public Output<string?> BasicAuthPassword { get; private set; } = null!;

        [Output("basicAuthUsername")]
        public Output<string?> BasicAuthUsername { get; private set; } = null!;

        [Output("databaseName")]
        public Output<string?> DatabaseName { get; private set; } = null!;

        [Output("isDefault")]
        public Output<bool?> IsDefault { get; private set; } = null!;

        [Output("jsonDatas")]
        public Output<ImmutableArray<Outputs.DataSourceJsonData>> JsonDatas { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        [Output("secureJsonDatas")]
        public Output<ImmutableArray<Outputs.DataSourceSecureJsonData>> SecureJsonDatas { get; private set; } = null!;

        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        [Output("url")]
        public Output<string?> Url { get; private set; } = null!;

        [Output("username")]
        public Output<string?> Username { get; private set; } = null!;


        /// <summary>
        /// Create a DataSource resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DataSource(string name, DataSourceArgs args, CustomResourceOptions? options = null)
            : base("grafana:/dataSource:DataSource", name, args ?? new DataSourceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DataSource(string name, Input<string> id, DataSourceState? state = null, CustomResourceOptions? options = null)
            : base("grafana:/dataSource:DataSource", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DataSource resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DataSource Get(string name, Input<string> id, DataSourceState? state = null, CustomResourceOptions? options = null)
        {
            return new DataSource(name, id, state, options);
        }
    }

    public sealed class DataSourceArgs : Pulumi.ResourceArgs
    {
        [Input("accessMode")]
        public Input<string>? AccessMode { get; set; }

        [Input("basicAuthEnabled")]
        public Input<bool>? BasicAuthEnabled { get; set; }

        [Input("basicAuthPassword")]
        public Input<string>? BasicAuthPassword { get; set; }

        [Input("basicAuthUsername")]
        public Input<string>? BasicAuthUsername { get; set; }

        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        [Input("isDefault")]
        public Input<bool>? IsDefault { get; set; }

        [Input("jsonDatas")]
        private InputList<Inputs.DataSourceJsonDataArgs>? _jsonDatas;
        public InputList<Inputs.DataSourceJsonDataArgs> JsonDatas
        {
            get => _jsonDatas ?? (_jsonDatas = new InputList<Inputs.DataSourceJsonDataArgs>());
            set => _jsonDatas = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("secureJsonDatas")]
        private InputList<Inputs.DataSourceSecureJsonDataArgs>? _secureJsonDatas;
        public InputList<Inputs.DataSourceSecureJsonDataArgs> SecureJsonDatas
        {
            get => _secureJsonDatas ?? (_secureJsonDatas = new InputList<Inputs.DataSourceSecureJsonDataArgs>());
            set => _secureJsonDatas = value;
        }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("url")]
        public Input<string>? Url { get; set; }

        [Input("username")]
        public Input<string>? Username { get; set; }

        public DataSourceArgs()
        {
        }
    }

    public sealed class DataSourceState : Pulumi.ResourceArgs
    {
        [Input("accessMode")]
        public Input<string>? AccessMode { get; set; }

        [Input("basicAuthEnabled")]
        public Input<bool>? BasicAuthEnabled { get; set; }

        [Input("basicAuthPassword")]
        public Input<string>? BasicAuthPassword { get; set; }

        [Input("basicAuthUsername")]
        public Input<string>? BasicAuthUsername { get; set; }

        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        [Input("isDefault")]
        public Input<bool>? IsDefault { get; set; }

        [Input("jsonDatas")]
        private InputList<Inputs.DataSourceJsonDataGetArgs>? _jsonDatas;
        public InputList<Inputs.DataSourceJsonDataGetArgs> JsonDatas
        {
            get => _jsonDatas ?? (_jsonDatas = new InputList<Inputs.DataSourceJsonDataGetArgs>());
            set => _jsonDatas = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("secureJsonDatas")]
        private InputList<Inputs.DataSourceSecureJsonDataGetArgs>? _secureJsonDatas;
        public InputList<Inputs.DataSourceSecureJsonDataGetArgs> SecureJsonDatas
        {
            get => _secureJsonDatas ?? (_secureJsonDatas = new InputList<Inputs.DataSourceSecureJsonDataGetArgs>());
            set => _secureJsonDatas = value;
        }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("url")]
        public Input<string>? Url { get; set; }

        [Input("username")]
        public Input<string>? Username { get; set; }

        public DataSourceState()
        {
        }
    }
}
