// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Grafana
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("grafana");
        /// <summary>
        /// Credentials for accessing the Grafana API.
        /// </summary>
        public static string? Auth { get; set; } = __config.Get("auth") ?? Utilities.GetEnv("GRAFANA_AUTH");

        /// <summary>
        /// URL of the root of the target Grafana server.
        /// </summary>
        public static string? Url { get; set; } = __config.Get("url") ?? Utilities.GetEnv("GRAFANA_URL");

    }
}
