// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class DataSourceJsonData
    {
        public readonly string? AssumeRoleArn;
        public readonly string AuthType;
        public readonly string? CustomMetricsNamespaces;
        public readonly string DefaultRegion;

        [OutputConstructor]
        private DataSourceJsonData(
            string? assumeRoleArn,

            string authType,

            string? customMetricsNamespaces,

            string defaultRegion)
        {
            AssumeRoleArn = assumeRoleArn;
            AuthType = authType;
            CustomMetricsNamespaces = customMetricsNamespaces;
            DefaultRegion = defaultRegion;
        }
    }
}
