// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi/config"
)

// Credentials for accessing the Grafana API.
func GetAuth(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "grafana:auth")
	if err == nil {
		return v
	}
	return getEnvOrDefault("", nil, "GRAFANA_AUTH").(string)
}

// URL of the root of the target Grafana server.
func GetUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "grafana:url")
	if err == nil {
		return v
	}
	return getEnvOrDefault("", nil, "GRAFANA_URL").(string)
}
