// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package grafana

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type AlertNotification struct {
	pulumi.CustomResourceState

	IsDefault pulumi.BoolPtrOutput `pulumi:"isDefault"`
	Name      pulumi.StringOutput  `pulumi:"name"`
	Settings  pulumi.MapOutput     `pulumi:"settings"`
	Type      pulumi.StringOutput  `pulumi:"type"`
}

// NewAlertNotification registers a new resource with the given unique name, arguments, and options.
func NewAlertNotification(ctx *pulumi.Context,
	name string, args *AlertNotificationArgs, opts ...pulumi.ResourceOption) (*AlertNotification, error) {
	if args == nil || args.Type == nil {
		return nil, errors.New("missing required argument 'Type'")
	}
	if args == nil {
		args = &AlertNotificationArgs{}
	}
	var resource AlertNotification
	err := ctx.RegisterResource("grafana:/alertNotification:AlertNotification", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAlertNotification gets an existing AlertNotification resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAlertNotification(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AlertNotificationState, opts ...pulumi.ResourceOption) (*AlertNotification, error) {
	var resource AlertNotification
	err := ctx.ReadResource("grafana:/alertNotification:AlertNotification", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AlertNotification resources.
type alertNotificationState struct {
	IsDefault *bool                  `pulumi:"isDefault"`
	Name      *string                `pulumi:"name"`
	Settings  map[string]interface{} `pulumi:"settings"`
	Type      *string                `pulumi:"type"`
}

type AlertNotificationState struct {
	IsDefault pulumi.BoolPtrInput
	Name      pulumi.StringPtrInput
	Settings  pulumi.MapInput
	Type      pulumi.StringPtrInput
}

func (AlertNotificationState) ElementType() reflect.Type {
	return reflect.TypeOf((*alertNotificationState)(nil)).Elem()
}

type alertNotificationArgs struct {
	IsDefault *bool                  `pulumi:"isDefault"`
	Name      *string                `pulumi:"name"`
	Settings  map[string]interface{} `pulumi:"settings"`
	Type      string                 `pulumi:"type"`
}

// The set of arguments for constructing a AlertNotification resource.
type AlertNotificationArgs struct {
	IsDefault pulumi.BoolPtrInput
	Name      pulumi.StringPtrInput
	Settings  pulumi.MapInput
	Type      pulumi.StringInput
}

func (AlertNotificationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*alertNotificationArgs)(nil)).Elem()
}
