// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class DataSourceJsonDataArgs : Pulumi.ResourceArgs
    {
        [Input("assumeRoleArn")]
        public Input<string>? AssumeRoleArn { get; set; }

        [Input("authType", required: true)]
        public Input<string> AuthType { get; set; } = null!;

        [Input("customMetricsNamespaces")]
        public Input<string>? CustomMetricsNamespaces { get; set; }

        [Input("defaultRegion", required: true)]
        public Input<string> DefaultRegion { get; set; } = null!;

        public DataSourceJsonDataArgs()
        {
        }
    }
}
